CREATE DATABASE NOTA_FISCAL_NORMALIZADA;

USE `NOTA_FISCAL_NORMALIZADA`;

CREATE TABLE `NOTA_FISCAL`(
	`NRO_NOTA`INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NM_CLIENTE` VARCHAR(256) NOT NULL,
    `END_CLIENTE` VARCHAR(256) NOT NULL,
    `NM_VENDEDOR` VARCHAR(256) NOT NULL,
    `DT_EMISSAO` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `VL_TOTAL` FLOAT NOT NULL
);

CREATE TABLE `PRODUTO` (
	`COD_PRODUTO` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `DESC_PRODUTO` VARCHAR(256) NOT NULL,
    `UN_MED` CHAR(2) NOT NULL,
    `VL_PRODUTO` FLOAT NOT NULL    
);

CREATE TABLE `ITEM_NOTA_FISCAL`(
	`NRO_NOTA`INT NOT NULL,
    `COD_PRODUTO` INT NOT NULL,
    `QTD_PRODUTO` INT NOT NULL,
    `VL_PRECO` FLOAT NOT NULL,
    `VL_TOTAL` FLOAT NOT NULL,
    PRIMARY KEY(NRO_NOTA, COD_PRODUTO),
    CONSTRAINT FK_NRO_NOTA_NOTA_FISCAL 
		FOREIGN KEY (NRO_NOTA) REFERENCES NOTA_FISCAL(NRO_NOTA),
    CONSTRAINT FK_COD_PRODUTO_PRODUTO 
		FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO)
);

-- 

INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES('Leite', 'LT', 4.50);

INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES('Desodorante', 'UN', 8.00);

INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES('Salame', 'KG', 40.00);

-- nota fiscal

INSERT INTO `NOTA_FISCAL`(NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL)
VALUES ('Aragorn', 'Terra Média', 'Bilbo', 100.00 );

INSERT INTO `NOTA_FISCAL`(NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL)
VALUES ('Gandalf', 'Terra Média', 'Frodo', 100.00 );

INSERT INTO `NOTA_FISCAL`(NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL)
VALUES ('Boromir', 'Mordor', 'Sam', 100.00 );

INSERT INTO `NOTA_FISCAL`(NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL)
VALUES ('Galadriel', 'Valinor', 'Saruman', 100.00 );

SELECT * FROM `NOTA_FISCAL`;

-- Itens da Nota

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (1, 1, 1, 4.50, 4.50);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (1, 2, 2, 40.00, 80.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (1, 3, 10, 100.00, 1000.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (2, 3, 10, 100.00, 1000.00);

--

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (2, 1, 1, 9.00, 9.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (2, 2, 2, 80.00, 160.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (2, 3, 10, 200.00, 2000.00);

--

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (3, 1, 1, 18.00, 18.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (3, 2, 2, 160.00, 320.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (3, 3, 10, 400.00, 4000.00);

--

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (4, 1, 1, 32.00, 32.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (4, 2, 2, 420.00, 840.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES (4, 3, 10, 800.00, 8000.00);

SELECT * FROM `ITEM_NOTA_FISCAL`;

--------------------------------------------------------------------------------------------------

-- INNER JOIN
-- Retona os registros quesão comuns ás duas tabelas
SELECT
	NF.NRO_NOTA, NF.NM_CLIENTE, 
    COUNT(INF.COD_PRODUTO) AS QTD, SUM(INF.VL_TOTAL) AS TOTAL
FROM
    NOTA_FISCAL AS NF
INNER JOIN ITEM_NOTA_FISCAL AS INF
ON NF.NRO_NOTA = INF.NRO_NOTA
GROUP BY NF.NRO_NOTA
ORDER BY QTD, TOTAL DESC;

-- INNER JOIN
SELECT 
NF.NRO_NOTA, NF.NM_CLIENTE, P.DESC_PRODUTO
FROM NOTA_FISCAL AS NF 
INNER JOIN ITEM_NOTA_FISCAL AS INF
    ON NF.NRO_NOTA = INF.NRO_NOTA
INNER JOIN PRODUTO AS P
    ON INF.COD_PRODUTO = P.COD_PRODUTO
ORDER BY NF.NRO_NOTA ASC;

-- LEFT JOIN
-- Retorna os registros que estão na tabela a esquerda
-- (mesmo que não estejam à direita) eosregistros da tabela à direita que são comuns a ela.

SELECT 
NF.NRO_NOTA, NF.NM_CLIENTE, P.DESC_PRODUTO
FROM NOTA_FISCAL AS NF 
LEFT JOIN ITEM_NOTA_FISCAL AS INF
    ON NF.NRO_NOTA = INF.NRO_NOTA
LEFT JOIN PRODUTO AS P
    ON INF.COD_PRODUTO = P.COD_PRODUTO
ORDER BY NF.NRO_NOTA ASC;

-- RIGHT JOIN
-- Usamos para exibir os registros que estão na tabela 
-- à direita mesmo que não estejam na tabela à 
-- esquerda e os registros da tabela à esquerda 
-- que são comuns à direita

SELECT 
NF.NRO_NOTA, NF.NM_CLIENTE, P.DESC_PRODUTO
FROM NOTA_FISCAL AS NF 
RIGHT JOIN ITEM_NOTA_FISCAL AS INF
    ON NF.NRO_NOTA = INF.NRO_NOTA
RIGHT JOIN PRODUTO AS P
    ON INF.COD_PRODUTO = P.COD_PRODUTO
ORDER BY NF.NRO_NOTA ASC;

-------------------------------------------------------------------------------------------------------

INSERT INTO `NOTA_FISCAL`(
NM_CLIENTE, 
END_CLIENTE, 
NM_VENDEDOR, 
VL_TOTAL)
VALUES ('Smeagol', 'Pántano', 'Sauron', 99.00 );

select * from nota_fiscal
where nm_cliente = 'Smeagol';

INSERT INTO `NOTA_FISCAL`(
NM_CLIENTE, 
END_CLIENTE, 
NM_VENDEDOR, 
VL_TOTAL)
VALUES ('Gimly', 'Montanha', 'Thorin', 9999.00 );

INSERT INTO `PRODUTO`(DESC_PRODUTO, UN_MED,VL_PRODUTO)
VALUES('Queijo', 'Kg', '30' );

INSERT INTO `PRODUTO`(DESC_PRODUTO, UN_MED,VL_PRODUTO)
VALUES('Copa', 'Kg', '70' );


